### ISSUE TITLE
Clear previously keywords.

### ISSUE THREAD

**Issue by naodya** [iamwebdesigner/jQuiteLight#1]
My search doesn't do a post back, rather it hides and shows elements according to the entered keywords. The problem I'm facing is, whenever I do a new search, the previously searched keywords still remain in the `<span class='marked-text'>keyword</span>`. How do I clear previous search keywords on submit?

**Comment by iamawebgeek** [comment]
In order to remove the highlight you need to find the necessary highlight object from the array and call its destroy method. In Usage section of README you can find the following example:
By this you will get the array of highligh objects:

``` js
var HIGHLIGHTS = $(".element-to-be-highlighted").data("marker");
```

If only one highligthing has been done, you can remove it like so:

``` js
// Destroy
HIGHLIGHTS[0].destroy();
```
